title: Personal Wiki
author:
  name: Saikat Banerjee
  url: https://saik.at/
  email:
description: > # this means to ignore newlines until "show_excerpts:"
  This site contains jupyter notebooks, miscellaneous links, and derivations for my own reference.
  This corner of the web has a very high entropy and nothing is really organized.
  If you look around, you may find interesting stuff.
show_drafts: false # set to true to show post listings on the homepage
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/banskt" }
    - { platform: github, user_url: "https://github.com/banskt" }
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/banskt" }
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

remote_theme: jekyll/minima
